# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tampildinas',
            name='nama_kabupaten_kota',
        ),
        migrations.DeleteModel(
            name='TampilDinas',
        ),
    ]
