# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0004_auto_20170613_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akunperusahaan',
            name='perusahaan',
        ),
        migrations.DeleteModel(
            name='AkunPerusahaan',
        ),
    ]
