# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0007_auto_20170623_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akunperusahaan',
            name='perusahaan',
        ),
    ]
