# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perusahaan', '0009_akunperusahaan_perusahaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akunperusahaan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='akunperusahaan',
            name='password',
        ),
        migrations.AddField(
            model_name='akunperusahaan',
            name='akun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
