# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0010_auto_20170629_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resign',
            name='aktif',
        ),
    ]
