# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0011_auto_20170702_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='resign',
            name='mulai_bekerja',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
