# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0012_resign_mulai_bekerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktif',
            name='perusahaan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perusahaan.Perusahaan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resign',
            name='perusahaan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='perusahaan.Perusahaan'),
            preserve_default=False,
        ),
    ]
